use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006009
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
SUBTYPES
coercions
subtypes
subtyping
instantiation
TODO
Organise
parameterized
parameterize
subtype
Robert
phaylon
Sedlacek
rs
Karen
Etheridge
ether
Dave
Rolsky
autarch
John
Napiorkowski
jjnapiork
Rafael
Kitover
rkitover
Florian
Ragwitz
rafl
Matt
Trout
mst
Tomas
Doran
t0m
bobtfish
Jesse
Luehrs
doy
Hans
Dieter
Pearcey
hdp
Graham
Knop
haarg
Paul
Fenwick
pjf
Kent
Fredric
kentfredric
Justin
Hunter
justin
lib
MooseX
Types
Base
CheckedUtilExports
Combine
Moose
TypeDecorator
UndefinedType
Util
Wrapper
